apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdpr
  namespace: biowerk
spec:
  template:
    spec:
      containers:
        - name: gdpr
          env:
            - name: ENVIRONMENT
              value: production
            - name: ENCRYPTION_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: gdpr-secrets
                  key: encryption_master_key
                  optional: false
